"use client";
import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
type Conversation={id:number;person:{id:number;name:string;email:string|null}|null;last_message:{body:string;created_at:string;sender_id:number}|null;unread_count:number};
type Message={id:number;body:string;sender_id:number;is_mine:boolean;sender?:{id:number;name:string};created_at:string};
export function MessagesWorkspace({conversationId}:{conversationId?:number}){const [conversations,setConversations]=useState<Conversation[]>([]);const [messages,setMessages]=useState<Message[]>([]);const [body,setBody]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 const loadConversations=useCallback(async()=>{try{const r=await fetch("/api/backend/conversations",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.message??"Unable to load messages.");setConversations(d);}catch(e){setError(e instanceof Error?e.message:"Unable to load messages.");}},[]);
 const loadMessages=useCallback(async()=>{if(!conversationId)return;try{const r=await fetch(`/api/backend/conversations/${conversationId}/messages`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.message??"Unable to load this conversation.");setMessages(d);}catch(e){setError(e instanceof Error?e.message:"Unable to load this conversation.");}},[conversationId]);
 useEffect(()=>{void loadConversations();},[loadConversations]);useEffect(()=>{void loadMessages();if(!conversationId)return;const timer=setInterval(()=>{void loadMessages();void loadConversations();},5000);return()=>clearInterval(timer);},[conversationId,loadMessages,loadConversations]);
 async function send(e:FormEvent){e.preventDefault();if(!body.trim()||!conversationId)return;setBusy(true);setError("");try{const r=await fetch(`/api/backend/conversations/${conversationId}/messages`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({body})});const d=await r.json();if(!r.ok)throw new Error(d.message??"Message could not be sent.");setBody("");await loadMessages();await loadConversations();}catch(e){setError(e instanceof Error?e.message:"Message could not be sent.");}finally{setBusy(false);}}
 const active=conversations.find(c=>c.id===conversationId);
 return <section className="module-page messages-page"><div className="module-heading"><div><p className="eyebrow">PRIVATE, ONE-TO-ONE CONVERSATIONS</p><h1>Messages</h1><p className="module-subtitle">A thoughtful space for direct workspace conversations.</p></div><Link className="button-secondary" href="/app/people">Find people <span>→</span></Link></div>{error&&<div className="work-alert">{error}</div>}<div className="messages-layout"><aside className="conversation-list"><div className="conversation-list-heading"><b>Conversations</b><span>{conversations.length}</span></div>{conversations.length?conversations.map(c=><Link className={`conversation-item ${conversationId===c.id?"conversation-active":""}`} href={`/app/messages/${c.id}`} key={c.id}><span className="conversation-avatar">{(c.person?.name??"?").split(/\s+/).map(p=>p[0]).slice(0,2).join("").toUpperCase()}</span><span className="conversation-copy"><b>{c.person?.name??"Workspace member"}</b><small>{c.last_message?.body??"Start the conversation"}</small></span>{!!c.unread_count&&<i className="unread-badge">{c.unread_count}</i>}</Link>):<div className="conversation-empty"><span>✦</span><p>Your conversations will appear here.</p><Link href="/app/people">Find someone to message</Link></div>}</aside><section className="message-thread">{conversationId?(<><header className="message-thread-heading"><span className="conversation-avatar">{(active?.person?.name??messages.at(-1)?.sender?.name??"?").split(/\s+/).map(p=>p[0]).slice(0,2).join("").toUpperCase()}</span><span><b>{active?.person?.name??messages.at(-1)?.sender?.name??"Conversation"}</b><small>Direct conversation</small></span></header><div className="message-history">{messages.length?messages.map(m=><article key={m.id} className={`message-bubble ${m.is_mine?"message-bubble-own":""}`}><small>{m.sender?.name??"Workspace member"}</small><p>{m.body}</p><time>{new Intl.DateTimeFormat(undefined,{hour:"numeric",minute:"2-digit"}).format(new Date(m.created_at))}</time></article>):<div className="thread-welcome"><span>✦</span><h2>Start with a hello</h2><p>Messages are private to the people in this conversation.</p></div>}</div><form className="message-composer" onSubmit={send}><textarea value={body} onChange={e=>setBody(e.target.value)} placeholder="Write a message…" rows={2} maxLength={5000}/><button className="button-primary" disabled={busy||!body.trim()}>{busy?"Sending…":"Send message"}</button></form></>):<div className="thread-welcome"><span>✦</span><h2>Your conversations, in one place</h2><p>Choose a conversation or find a workspace member to begin.</p><Link className="button-primary" href="/app/people">Browse people</Link></div>}</section></div><div className="module-footnote">Messages update automatically every few seconds. Group rooms are coming in a later module.</div></section>;
}
