"use client";
import { FormEvent, useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { assistantVoiceOptions, resolveAssistantVoice, type AssistantVoiceId } from "@/lib/assistant-voice";
import { ProfileAvatar } from "@/components/ProfileAvatar";

type Theme = { mode: string; font_family: string; font_size: number; colors: { accent: string; heading: string; text: string; background: string; surface: string } };
type Profile = { name: string; email: string; job_title: string; department: string; phone: string; location: string; bio: string; timezone: string; locale: string; profile_visibility: string; preferences: { theme?: Partial<Theme>; notify_in_app?: boolean; notify_email?: boolean; notify_browser?: boolean; assistant_name?: string; assistant_voice?: AssistantVoiceId; assistant_language?: "en-IN" | "hi-IN"; avatar?: string | null } };
const defaults: Theme = { mode: "light", font_family: "Aptos", font_size: 17, colors: { accent: "#655cdd", heading: "#292d40", text: "#42475a", background: "#f6f7fb", surface: "#ffffff" } };
const colorFields: Array<{ key: keyof Theme["colors"]; label: string; help: string }> = [
  { key: "accent", label: "Accent color", help: "Buttons and highlights" },
  { key: "heading", label: "Headings", help: "Titles and section headings" },
  { key: "text", label: "Body text", help: "Paragraphs and labels" },
  { key: "background", label: "Workspace background", help: "Page background" },
  { key: "surface", label: "Cards and panels", help: "Content surfaces" },
];
const supportedTimezones = () => { const values = typeof Intl.supportedValuesOf === "function" ? Intl.supportedValuesOf("timeZone") : ["UTC", "America/New_York", "America/Los_Angeles", "Europe/London", "Europe/Paris", "Asia/Dubai", "Asia/Singapore", "Australia/Sydney"]; return Array.from(new Set([...values.filter(zone => zone !== "Asia/Calcutta"), "Asia/Kolkata"])).sort((a,b)=>a.localeCompare(b)); };
const canonicalTimezone = (timezone: string) => ["Asia/Calcutta", "Asia/Kolkatta"].includes(timezone) ? "Asia/Kolkata" : timezone;
function mergedTheme(theme?: Partial<Theme>): Theme { return { ...defaults, ...theme, font_family: theme?.font_family === "system" ? "Aptos" : theme?.font_family ?? defaults.font_family, colors: { ...defaults.colors, ...theme?.colors } }; }

export default function ProfilePage() {
  const router = useRouter();
  const [profile, setProfile] = useState<Profile | null>(null); const [avatar,setAvatar]=useState<string|null>(null); const avatarInput=useRef<HTMLInputElement>(null); const [cropSource,setCropSource]=useState<string|null>(null); const [cropZoom,setCropZoom]=useState(1); const [theme, setTheme] = useState(defaults); const [assistantName,setAssistantName]=useState("Kriyabot Assistant"); const [assistantVoice,setAssistantVoice]=useState<AssistantVoiceId>("india_female_warm"); const [assistantLanguage,setAssistantLanguage]=useState<"en-IN"|"hi-IN">("en-IN"); const [voiceNote,setVoiceNote]=useState(""); const [notifications, setNotifications] = useState({ notify_in_app: true, notify_email: true, notify_browser: false });
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [saved, setSaved] = useState(false); const [error, setError] = useState("");
  useEffect(()=>()=>{if(cropSource)URL.revokeObjectURL(cropSource)},[cropSource]);
  const zones = useMemo(() => supportedTimezones(), []);
  const load = useCallback(async () => { setLoading(true); try { const response = await fetch("/api/backend/me", { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.message ?? "Could not load your profile."); setProfile({ name: data.name ?? "", email: data.email ?? "", job_title: data.job_title ?? "", department: data.department ?? "", phone: data.phone ?? "", location: data.location ?? "", bio: data.bio ?? "", timezone: canonicalTimezone(data.timezone ?? "UTC"), locale: data.locale ?? "en", profile_visibility: data.profile_visibility ?? "workspace", preferences: data.preferences ?? {} }); setAvatar(data.preferences?.avatar ?? null); setAssistantName(data.preferences?.assistant_name ?? "Kriyabot Assistant"); setAssistantVoice(data.preferences?.assistant_voice ?? "india_female_warm"); setAssistantLanguage(data.preferences?.assistant_language ?? (data.locale === "hi" ? "hi-IN" : "en-IN")); const nextTheme = mergedTheme(data.preferences?.theme); setTheme(nextTheme); setNotifications({ notify_in_app: data.preferences?.notify_in_app ?? true, notify_email: data.preferences?.notify_email ?? true, notify_browser: data.preferences?.notify_browser ?? false }); window.dispatchEvent(new CustomEvent("taskflow:theme-preview", { detail: nextTheme })); setError(""); } catch (e) { setError(e instanceof Error ? e.message : "Could not load your profile."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  function updateTheme(next: Theme) { setTheme(next); setSaved(false); window.dispatchEvent(new CustomEvent("taskflow:theme-preview", { detail: next })); }
  function updateColor(key: keyof Theme["colors"], value: string) { updateTheme({ ...theme, colors: { ...theme.colors, [key]: value } }); }
  function chooseAvatarFile(event: React.ChangeEvent<HTMLInputElement>) { const file=event.target.files?.[0]; if(!file)return; if(!["image/jpeg","image/png","image/webp"].includes(file.type)){setError("Choose a PNG, JPG, or WebP image.");event.target.value="";return;} if(file.size>20_000_000){setError("Choose an image smaller than 20 MB.");event.target.value="";return;} setCropSource(URL.createObjectURL(file));setCropZoom(1);setError("");event.target.value=""; }
  async function saveAvatarCrop() { if(!cropSource)return; try { const image=new Image(); image.src=cropSource; await image.decode(); const side=Math.min(image.naturalWidth,image.naturalHeight)/cropZoom; const canvas=document.createElement("canvas");canvas.width=512;canvas.height=512;const context=canvas.getContext("2d");if(!context)throw new Error("Photo cropping is unavailable in this browser.");context.drawImage(image,(image.naturalWidth-side)/2,(image.naturalHeight-side)/2,side,side,0,0,512,512);let quality=.86;let result=canvas.toDataURL("image/jpeg",quality);while(result.length>390_000&&quality>.48){quality-=.08;result=canvas.toDataURL("image/jpeg",quality);}setAvatar(result);setCropSource(null);setSaved(false);setError(""); } catch (cause) { setError(cause instanceof Error?cause.message:"This image could not be cropped."); } }
  function detectDeviceTimezone() { const detected=canonicalTimezone(Intl.DateTimeFormat().resolvedOptions().timeZone||"UTC");if(!zones.includes(detected)){setError(`The device reported ${detected}, which is not in the available list. Choose a time zone manually.`);return;}setProfile(current=>current?{...current,timezone:detected}:current);setSaved(false);setError(""); }
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!profile) return; setSaving(true); setSaved(false); setError(""); const form = new FormData(event.currentTarget); const body = { name: form.get("name"), job_title: form.get("job_title"), department: form.get("department"), phone: form.get("phone"), location: form.get("location"), bio: form.get("bio"), timezone: form.get("timezone"), locale: form.get("locale"), profile_visibility: form.get("profile_visibility"), preferences: { theme, avatar, assistant_name: assistantName, assistant_voice: assistantVoice, assistant_language: assistantLanguage, ...notifications } }; try { const response = await fetch("/api/backend/me", { method: "PATCH", headers: { "Content-Type": "application/json", Accept: "application/json" }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) throw new Error(data.message ?? "Could not save your profile."); setSaved(true); window.dispatchEvent(new CustomEvent("taskflow:theme-preview", { detail: theme })); router.refresh(); } catch (e) { setError(e instanceof Error ? e.message : "Could not save your profile."); } finally { setSaving(false); } }
  function previewAssistantVoice() { if (!("speechSynthesis" in window)) { setError("Voice playback is not available in this browser."); return; } window.speechSynthesis.cancel(); const hindi = assistantLanguage === "hi-IN"; const utterance = new SpeechSynthesisUtterance(hindi ? `नमस्ते ${profile?.name || ""}। मैं ${assistantName} हूँ।` : `Hello ${profile?.name || "there"}. I’m ${assistantName}. I’ll use this voice for your greetings and spoken replies.`); const voices = window.speechSynthesis.getVoices(); const selected = resolveAssistantVoice(assistantVoice, voices); const hindiVoice = hindi ? voices.find(voice => voice.lang.toLowerCase().replaceAll("_", "-").startsWith("hi-in")) : undefined; utterance.voice = hindi ? (hindiVoice ?? null) : (selected.voice ?? null); utterance.lang = hindi ? "hi-IN" : selected.lang; utterance.rate = selected.rate; utterance.pitch = selected.pitch; utterance.volume = 0.9; const isIndian = selected.voice?.lang.toLowerCase().replaceAll("_", "-").startsWith("en-in"); setVoiceNote(hindi ? (hindiVoice ? `Previewing ${hindiVoice.name}, a Hindi voice available on this device.` : "Hindi speech is selected. This device needs an installed Hindi voice for spoken playback; the assistant will still reply in Hindi in text.") : isIndian ? `Previewing ${selected.voice?.name}, an Indian English voice available on this device.` : selected.voice ? `That exact Indian English voice is not installed. Previewing the closest matching voice: ${selected.voice.name}.` : "No speech voice is installed in this browser; the browser's default voice will be used."); window.speechSynthesis.speak(utterance); }
  if (loading && !profile) return <section className="profile-settings-page"><div className="profile-loading"><span/><span/><span/></div></section>;
  if (!profile) return <section className="profile-settings-page"><div className="work-alert">{error || "Your profile could not be loaded."}</div><button className="button-secondary" onClick={() => void load()}>Try again</button></section>;

  return <section className="profile-settings-page">
    <div className="profile-settings-heading"><div><p className="eyebrow">MAKE KRIYABOT FEEL LIKE YOURS</p><h1>Profile & preferences</h1><p>Update your personal details, workspace appearance, and how we reach you.</p></div><div className="profile-identity"><ProfileAvatar value={avatar} name={profile.name} className="profile-identity-avatar"/><div><b>{profile.name}</b><small>{profile.email}</small></div></div></div>
    {error && <div className="work-alert" role="alert">{error}</div>}
    <form onSubmit={save} className="profile-settings-form">
      <section className="profile-section"><header><span className="profile-section-icon profile-icon-violet">◎</span><div><h2>Personal details</h2><p>Details that help your teammates recognize you.</p></div><span className="profile-section-step">01</span></header><div className="profile-form-grid"><div className="profile-field-wide profile-avatar-settings"><div><ProfileAvatar value={avatar} name={profile.name} className="profile-settings-avatar"/><span><b>Profile picture</b><small>Upload a photo or choose a color avatar.</small></span></div><input ref={avatarInput} className="profile-avatar-file" type="file" accept="image/png,image/jpeg,image/webp" onChange={chooseAvatarFile}/><div className="avatar-actions"><button type="button" className="button-secondary avatar-upload-button" onClick={()=>avatarInput.current?.click()}>Upload photo</button><div className="avatar-presets" aria-label="Choose an avatar color">{["violet","orange","blue","green","rose","teal"].map(color=><button key={color} type="button" aria-label={`${color} avatar`} aria-pressed={avatar===`preset:${color}`} className={`avatar-preset-button ${avatar===`preset:${color}`?"avatar-preset-active":""}`} onClick={()=>{setAvatar(`preset:${color}`);setSaved(false)}}><ProfileAvatar value={`preset:${color}`} name={profile.name}/></button>)}</div><button type="button" className="avatar-remove-button" onClick={()=>{setAvatar(null);setSaved(false)}}>Remove</button></div></div><label><span>Full name</span><input name="name" required maxLength={120} defaultValue={profile.name}/></label><label><span>Email address</span><input value={profile.email} readOnly/><small>Email changes are managed through account security.</small></label><label><span>Job title</span><input name="job_title" maxLength={120} placeholder="e.g. Product designer" defaultValue={profile.job_title}/></label><label><span>Department</span><input name="department" maxLength={120} placeholder="e.g. Product & design" defaultValue={profile.department}/></label><label><span>Phone</span><input name="phone" type="tel" maxLength={40} autoComplete="tel" placeholder="Add a contact number" defaultValue={profile.phone}/></label><label><span>Location</span><input name="location" maxLength={160} placeholder="City or region" defaultValue={profile.location}/></label><label className="profile-field-wide"><span>About you</span><textarea name="bio" maxLength={2000} rows={3} placeholder="A few lines about what you work on…" defaultValue={profile.bio}/><small>Visible to workspace members who can view your profile.</small></label></div></section>

      <section className="profile-section"><header><span className="profile-section-icon profile-icon-blue">◷</span><div><h2>Regional & privacy</h2><p>Choose how dates and your profile appear to others.</p></div><span className="profile-section-step">02</span></header><div className="profile-form-grid"><label><span>Time zone</span><div className="timezone-control"><select name="timezone" value={profile.timezone} onChange={event=>setProfile(current=>current?{...current,timezone:event.target.value}:current)}>{!zones.includes(profile.timezone) && <option value={profile.timezone}>{profile.timezone}</option>}{zones.map(zone => <option key={zone} value={zone}>{zone === "Asia/Kolkata" ? "Kolkata, India · Asia/Kolkata" : zone.replaceAll("_", " ")}</option>)}</select><button type="button" className="button-secondary" onClick={detectDeviceTimezone}>Use device time zone</button></div><small>Detected from your device settings; Kriyabot does not need your precise location.</small></label><label><span>Language</span><select name="locale" defaultValue={profile.locale}><option value="en">English</option><option value="hi">हिन्दी · Hindi</option><option value="es">Español</option><option value="fr">Français</option><option value="de">Deutsch</option><option value="ar">العربية · Arabic</option></select></label><label><span>Profile visibility</span><select name="profile_visibility" defaultValue={profile.profile_visibility}><option value="workspace">Workspace members</option><option value="private">Private</option></select><small>Private profiles are hidden from the People directory.</small></label></div></section>

      <section className="profile-section"><header><span className="profile-section-icon profile-icon-violet">✦</span><div><h2>Your AI assistant</h2><p>Choose its name and a gentle speaking voice.</p></div><span className="profile-section-step">03</span></header><div className="profile-form-grid"><label><span>Assistant name</span><input value={assistantName} onChange={event=>{setAssistantName(event.target.value);setSaved(false)}} required minLength={2} maxLength={40} placeholder="e.g. Nova"/><small>Tap “Hey {assistantName || "Nova"}” in the assistant window to grant microphone access. Wake words work while this page is open.</small></label><label><span>Spoken voice</span><select value={assistantVoice} onChange={event=>{setAssistantVoice(event.target.value as AssistantVoiceId);setSaved(false);setVoiceNote("")}}>{assistantVoiceOptions.map(option=><option key={option.id} value={option.id}>{option.label}</option>)}</select><small>Five gentle male and female choices. The closest installed device voice is used.</small></label><label><span>AI preferred language</span><select value={assistantLanguage} onChange={event=>{setAssistantLanguage(event.target.value as "en-IN"|"hi-IN");setSaved(false);setVoiceNote("")}}><option value="en-IN">English</option><option value="hi-IN">हिन्दी · Hindi</option></select><small>Sets the welcome message, replies, and voice input. Hindi commands are saved in English.</small></label><div className="profile-field-wide profile-voice-preview"><button type="button" className="button-secondary" onClick={previewAssistantVoice}>▶ Preview voice</button>{voiceNote&&<small role="status">{voiceNote}</small>}</div></div></section>

      <section className="profile-section profile-appearance-section"><header><span className="profile-section-icon profile-icon-amber">✦</span><div><h2>Appearance</h2><p>Set your font, reading size, and the colors used across your workspace.</p></div><span className="profile-section-step">04</span></header><div className="appearance-controls"><div className="appearance-top-controls"><label><span>Font family</span><select value={theme.font_family} onChange={event => updateTheme({ ...theme, font_family: event.target.value })}><option value="Aptos">Aptos · Modern</option><option value="Tahoma">Tahoma · Clear</option><option value="Verdana">Verdana</option><option value="Georgia">Georgia</option></select></label><label className="font-size-control"><span>Font size <b>{theme.font_size}px</b></span><input type="range" min={12} max={24} step={1} value={theme.font_size} onChange={event => updateTheme({ ...theme, font_size: Number(event.target.value) })}/><small>Adjusts the overall workspace scale.</small></label></div><div className="theme-color-grid">{colorFields.map(field => <label className="theme-color-control" key={field.key}><span className="theme-color-swatch" style={{ backgroundColor: theme.colors[field.key] }}><input type="color" value={theme.colors[field.key]} onChange={event => updateColor(field.key, event.target.value)} aria-label={field.label}/></span><span><b>{field.label}</b><small>{field.help}</small></span><code>{theme.colors[field.key].toUpperCase()}</code></label>)}</div><div className="theme-preview" style={{ background: theme.colors.background, color: theme.colors.text, fontFamily: theme.font_family === "Georgia" ? "Georgia, serif" : theme.font_family === "Tahoma" ? "Tahoma, sans-serif" : theme.font_family === "Verdana" ? "Verdana, sans-serif" : "Aptos, Segoe UI Variable, Segoe UI, sans-serif" }}><div className="theme-preview-label">LIVE PREVIEW</div><article style={{ background: theme.colors.surface }}><span style={{ color: theme.colors.accent }}>✦ YOUR WORKSPACE</span><h3 style={{ color: theme.colors.heading }}>A space that feels like yours</h3><p style={{ color: theme.colors.text }}>Your choices will carry across Kriyabot screens and preferences.</p><button type="button" style={{ background: theme.colors.accent }}>Accent button</button></article></div></div></section>

      <section className="profile-section"><header><span className="profile-section-icon profile-icon-green">♧</span><div><h2>Notifications</h2><p>Choose which updates you’d like to receive.</p></div><span className="profile-section-step">05</span></header><div className="notification-preferences">{([{ key: "notify_in_app", title: "In-app notifications", note: "Updates and reminders inside Kriyabot" }, { key: "notify_email", title: "Email notifications", note: "Important updates sent to your email" }, { key: "notify_browser", title: "Browser notifications", note: "Desktop notifications in your browser" }] as const).map(item => <label className="notification-preference" key={item.key}><span><b>{item.title}</b><small>{item.note}</small></span><input type="checkbox" checked={notifications[item.key]} onChange={event => { setNotifications(current => ({ ...current, [item.key]: event.target.checked })); setSaved(false); }}/></label>)}</div></section>
      <footer className="profile-save-bar"><span>{saved ? <><i className="save-check">✓</i> Your preferences are saved.</> : "Your choices are saved to your account."}</span><button className="button-primary" disabled={saving}>{saving ? "Saving preferences…" : "Save changes"}</button></footer>
    </form>
    {cropSource&&<div className="avatar-crop-backdrop" role="presentation"><section className="avatar-crop-dialog" role="dialog" aria-modal="true" aria-labelledby="avatar-crop-title"><header><div><h2 id="avatar-crop-title">Crop your profile photo</h2><p>Drag the zoom control to frame a square. The saved photo is resized and compressed automatically.</p></div><button type="button" aria-label="Cancel crop" onClick={()=>setCropSource(null)}>×</button></header><div className="avatar-crop-preview"><img src={cropSource} alt="Preview of profile photo crop" style={{transform:`scale(${cropZoom})`}}/></div><label className="avatar-crop-zoom"><span>Zoom</span><input type="range" min="1" max="2.5" step="0.05" value={cropZoom} onChange={event=>setCropZoom(Number(event.target.value))}/></label><footer><button type="button" className="button-secondary" onClick={()=>setCropSource(null)}>Cancel</button><button type="button" className="button-primary" onClick={()=>void saveAvatarCrop()}>Use this photo</button></footer></section></div>}
  </section>;
}
