"use client";
import { ChangeEvent, useCallback, useEffect, useMemo, useState } from "react";
type FileItem = { id: number; task_id?: number; kind: "workspace" | "task"; name: string; mime_type: string; size: number; uploaded_at: string; uploader?: string | null; can_delete: boolean; url: string; context?: string };
const fileSize = (n: number) => n < 1024 * 1024 ? `${Math.max(1, Math.round(n / 1024))} KB` : `${(n / 1024 / 1024).toFixed(1)} MB`;
const fileType = (mime: string) => mime.startsWith("image/") ? "Image" : mime === "application/pdf" ? "PDF" : mime.includes("word") || mime.includes("document") ? "Document" : mime.includes("sheet") || mime.includes("excel") ? "Spreadsheet" : mime.includes("presentation") || mime.includes("powerpoint") ? "Presentation" : "File";
const fileIcon = (mime: string) => mime.startsWith("image/") ? "▧" : mime === "application/pdf" ? "PDF" : mime.includes("sheet") || mime.includes("excel") ? "XLS" : mime.includes("word") || mime.includes("document") ? "DOC" : "FILE";
export default function FilesPage() {
  const [files, setFiles] = useState<FileItem[]>([]); const [kind, setKind] = useState("all"); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { try { const response = await fetch("/api/backend/files", { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.message ?? "Unable to load files."); setFiles(data); setError(""); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load files."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const shown = useMemo(() => files.filter(file => kind === "all" || file.kind === kind), [files, kind]);
  async function upload(event: ChangeEvent<HTMLInputElement>) { const input = event.currentTarget; const selected = Array.from(input.files ?? []); if (!selected.length) return; setBusy(true); setError(""); try { for (const file of selected) { const form = new FormData(); form.append("file", file); const response = await fetch("/api/backend/files", { method: "POST", body: form }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.message ?? `Couldn’t upload ${file.name}.`); } await load(); } catch (e) { setError(e instanceof Error ? e.message : "Couldn’t upload the file."); } finally { setBusy(false); input.value = ""; } }
  async function remove(file: FileItem) { if (!window.confirm(`Remove “${file.name}” from the workspace library?`)) return; try { const response = await fetch(`/api/backend/files/${file.id}`, { method: "DELETE" }); if (!response.ok) { const data = await response.json().catch(() => ({})); throw new Error(data.message ?? "Couldn’t remove this file."); } await load(); } catch (e) { setError(e instanceof Error ? e.message : "Couldn’t remove this file."); } }
  return <section className="module-page files-module">
    <div className="module-heading"><div><p className="eyebrow">A SHARED HOME FOR YOUR WORK</p><h1>Files</h1><p className="module-subtitle">Find documents in your workspace or attached to a task.</p></div><label className={`button-primary file-upload-button ${busy ? "disabled" : ""}`}>＋ {busy ? "Uploading…" : "Upload a file"}<input type="file" multiple disabled={busy} accept=".jpg,.jpeg,.png,.webp,.gif,.pdf,.txt,.csv,.doc,.docx,.xls,.xlsx,.ppt,.pptx" onChange={upload}/></label></div>
    {error && <div className="work-alert">{error}</div>}
    <div className="files-summary"><div className="files-summary-mark">↥</div><div><b>Private storage, easy access</b><p>Files are available to approved workspace members. Upload images, PDF, Office documents, text, or CSV up to 10 MB.</p></div><span className="files-summary-count"><b>{files.length}</b><small>Total files</small></span></div>
    <div className="files-directory-card"><div className="files-directory-toolbar"><div><h2>File library</h2><p>{shown.length} {shown.length === 1 ? "file" : "files"} shared with you</p></div><label className="files-filter"><span>⌕</span><select value={kind} onChange={event => setKind(event.target.value)} aria-label="Filter files"><option value="all">All files</option><option value="workspace">Workspace library</option><option value="task">Task attachments</option></select></label></div>
      <div className="files-table-scroll"><table className="files-table"><thead><tr><th>FILE NAME</th><th>LOCATION</th><th>SHARED BY</th><th>FILE SIZE</th><th>ADDED</th><th><span className="visually-hidden">Actions</span></th></tr></thead><tbody>
        {loading ? [1, 2, 3, 4].map(i => <tr className="files-loading-row" key={i}><td colSpan={6}><span/><span/></td></tr>) : shown.map(file => <tr key={`${file.kind}-${file.id}`}><td><div className="library-file"><a href={file.url} target="_blank" rel="noreferrer" className={`library-file-icon ${file.mime_type.startsWith("image/") ? "library-image-icon" : ""}`}>{file.mime_type.startsWith("image/") ? <img src={file.url} alt="" loading="lazy"/> : fileIcon(file.mime_type)}</a><span><a href={file.url} target="_blank" rel="noreferrer" className="library-file-name" title={file.name}>{file.name}</a><small>{fileType(file.mime_type)}</small></span></div></td><td><span className={`file-location ${file.kind}`}><i>{file.kind === "task" ? "✓" : "▦"}</i>{file.context ?? "Workspace library"}</span></td><td><span className="files-uploader">{file.uploader ?? "Workspace member"}</span></td><td><span className="files-size">{fileSize(file.size)}</span></td><td><span className="files-date">{new Intl.DateTimeFormat(undefined, { month: "short", day: "numeric", year: "numeric" }).format(new Date(file.uploaded_at))}</span></td><td><div className="files-row-actions"><a href={`${file.url}?download=1`} className="files-download-button" aria-label={`Download ${file.name}`} title="Download">↓</a>{file.kind === "workspace" && file.can_delete && <button className="files-remove-button" onClick={() => void remove(file)} aria-label={`Remove ${file.name}`} title="Remove">×</button>}</div></td></tr>)}
      </tbody></table></div>
      {!loading && !shown.length && <div className="files-empty"><span>▧</span><h2>{files.length ? "No files in this view" : "Your file library is ready"}</h2><p>{files.length ? "Choose another filter to see more files." : "Upload a workspace document or add an attachment to a task. Your files will appear here."}</p>{!files.length && <label className="button-primary file-upload-button">＋ Upload your first file<input type="file" multiple onChange={upload}/></label>}</div>}
      <footer className="files-directory-footer"><span>🔒 Stored privately</span><small>Only approved members of this workspace can access these files.</small></footer>
    </div>
  </section>;
}
